### ISSUE TITLE
Unable to use Metal feature on Mac M1 Max (32 GB)

### ISSUE THREAD

**Issue by valiksb** [tazz4843/whisper-rs#108]
I'm fairly new to Rust and I wanted to start with a project that allows me to learn it while I also do something that I like and that is Whisper. whisper-rs seems like the ideal solution for this but I got a bit into some problems, see below

1. I created a brand new Rust project and copied https://github.com/tazz4843/whisper-rs/blob/master/examples/audio_transcription.rs and renamed it main.rs
2. made the suggested changes to my Cargo.toml
`[dependencies]
hound = "3"
whisper-rs = { version = "0.10.0" }`
3. Then I did `cargo run`
4. It worked fine but it took took long compared to whisper.cpp

I added this line `    println!("[{}]", print_system_info());` to see what was been used and this is the output
`[AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | METAL = 0 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 | ]`

then I enable Metal with
`features = ["metal"]` and run again, I got this sysinfo and a ASSERT
`[AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | METAL = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 | ]`
and this is the ASSERT
`ggml_metal_graph_compute: command buffer 0 failed with status 5
GGML_ASSERT: /path_to/my_whisper_sample/target/release/build/whisper-rs-sys-2c6c0c9736fdf6b6/out/whisper.cpp/ggml-metal.m:1611: false`

I dont believe this to be a bug, but I was not sure were to post this question/issue I'm having

Thanks in advance

**Comment by valiksb** [comment]
thanks. Let me try that

**Comment by magnusanderson-wk** [comment]
Did you figure anything out? I learned that if you copy the files explicitely `ggml-metal.h, ggml-metal.m, ggml-metal.metal` into the current working directory, (I think whisper.cpp) it will try a few paths and eventually load them. But inference doesn't work. This is frustrating as I would rather use rust for my programs compared to c++.

**Comment by dev-msp** [comment]
(I'm using an M1 Pro on 13.6.2)

I'm new to debugging Rust lib build steps, so I'm sure there's terminology I'm not using that would make this clearer!

I tried cloning this project  and adding a missing file (`ggml-common.h`) to the include list in the sys directory's `Cargo.toml` and now I find that the main issue is the [inflexible way](https://github.com/ggerganov/whisper.cpp/blob/ac283dbce7d42735e3ed985329037bf23fe180aa/ggml-metal.m#L333) that `whisper.cpp` tries to source the Metal files.

At runtime, it either looks in an environment variable  or falls back to the current directory, neither of which correspond the location of the Metal files, which end up in the Rust build directory.

I'm not sure if whisper.cpp needs patching to fix this, or if there is some magic we can do in the `whisper-rs` build process to make runtime behavior work cleanly and out of the box.

But I can report that when I set the `GGML_METAL_PATH_RESOURCES` environment variable at the right `target/` subfolder (specifically the `out` directory under whisper-rs-sys), inference works properly and with the expected speed.

Also - the log trampoline doesn't seem to capture the `GGML_METAL_LOG_{LEVEL}` calls.

**Comment by tazz4843** [comment]
> But I can report that when I set the GGML_METAL_PATH_RESOURCES environment variable at the right target/ subfolder (specifically the out directory under whisper-rs-sys), inference works properly and with the expected speed.

If this is all it takes then this might be an easy fix. I can draft a PR.

**Comment by dev-msp** [comment]
Oh awesome - I wasn't sure if we'd really need to set this environment variable at runtime to make it work, or if we do, whether that's acceptable practice.

**Comment by tazz4843** [comment]
If we need to set it at runtime I think it would be best to raise an upstream issue, but I think we'll be able to do it in build.rs without issues based off what you've said.

**Comment by tazz4843** [comment]
See 39042a8a15d1b49fc6fed4dbf318d0bb8984a6f8, try branch `try-fix-metal-build` to see if it works.

**Comment by dev-msp** [comment]
Awesome - If I understand correctly now, I think my original description was slightly off - it should be the `whisper.cpp` dir, not its parent(?) - the build dir for `whisper-rs-sys`.

**Comment by tazz4843** [comment]
Sorry that took me a bit to get back to: maybe 1e3adf1c490682a3b1f82a045a4232f116629868

**Comment by dev-msp** [comment]
@eftychis Yes, getting same thing on same hardware, though I'm on 13.6. Also runs fine when the variable is set at runtime.

**Comment by hlhr202** [comment]
My solution is to just copy the "ggml-metal.metal" file from out dir where whisper.cpp folder exists to the CWD
but again GGML_METAL_LOG is not captured by whisper_log_trampoline in the rust side

**Comment by hlhr202** [comment]
https://github.com/tazz4843/whisper-rs/pull/148
I have just created a naive fix. Anyone can have a try here?

**Comment by thebabush** [comment]
works using @bedesv cargo.toml line

**Comment by tazz4843** [comment]
New release on crates.io is out with a fix, closing.
