### ISSUE TITLE
there is newest version 0.10.1 in crates.io?

### ISSUE THREAD

**Issue by ChaoII** [tazz4843/whisper-rs#118]
hello,
I have add denpendencies for whisper-rs for 0.10.0,but i cant use the `param.set_init_prompt()` method. But I cant get the 0.10.1 version use cargo add command.

**Comment by tazz4843** [comment]
Sorry, was taking a bit of a break from GitHub. I don't tend to publish new versions until a large amount of patches and fixes are rolled in. For now, you can simply use the repository itself as a dependency.

**Comment by tazz4843** [comment]
0.11 published
