### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by sloganking** [tazz4843/whisper-rs#12]
Is this library currently single threaded CPU only?

**Comment by tazz4843** [comment]
This library is just a thin wrapper over whisper.cpp: https://github.com/ggerganov/whisper.cpp

You'd need to check upstream to see, and as of late I believe it is still CPU only, however parallelization has been added recently. If you're on an Apple Silicon Mac, apparently it is GPU accelerated, but as I don't have one I'm unable to test at all there.

**Comment by sloganking** [comment]
https://github.com/ggerganov/whisper.cpp/issues/61

I see. Looks like no GPU support planned in the near future. Thanks anyways!

**Comment by framp** [comment]
There is a branch with GPU support and some instructions on how to get it running but still no official support: https://github.com/ggerganov/whisper.cpp/issues/220
