### ISSUE TITLE
Documentation for 0.10.0 on docs.rs is broken 

### ISSUE THREAD

**Issue by ClementTsang** [tazz4843/whisper-rs#120]
Was trying to use this and look up the documentation on `docs.rs`, and noticed that it's broken with an error:

![image](https://github.com/tazz4843/whisper-rs/assets/34804052/3fd22bf9-9eea-45eb-a3df-f82f38edf0a9)

Looking at the [build logs](https://docs.rs/crate/whisper-rs/0.10.0/builds/1032888) points to something being broken with simd? I can submit a PR to try and fix it if that's of interest.

**Comment by ClementTsang** [comment]
Ah, I just actually saw https://github.com/tazz4843/whisper-rs/commit/249b7321c99e2578c47364c9982ff5b0e57f3605 - that might end up fixing it.

**Comment by tazz4843** [comment]
Will publish 0.11 to fix this hopefully now that the SIMD fns are removed.

**Comment by elpiel** [comment]
Awesome! Would be great to have the docs.rs

**Comment by tazz4843** [comment]
0.11 published, did a oopsie while removing SIMD and republished 0.11.1 which fixes this.
