### ISSUE TITLE
CUDA problem

### ISSUE THREAD

**Issue by Dorbmon** [tazz4843/whisper-rs#126]
When I set 
`whisper-rs = { version = "0.10.0", features=["cuda"] }`
The result of `full_get_segment_text` is always only string: " Nay". But once I use the CPU, the result is normal.

**Comment by thewh1teagle** [comment]
How did you compiled with cuda?
I want to add cuda support for [vibe](https://github.com/thewh1teagle/vibe) but I'm not sure where to get cuda from and what exact features / flags to enable in whisper-rs

**Comment by Dorbmon** [comment]
@thewh1teagle From Cargo.toml, you can use like this:
`whisper-rs = { version = "0.10.0", features=["cuda"] }`

Let me know if you encounter the same problem.

**Comment by tazz4843** [comment]
Likely an upstream issue, not much we can do here. Gonna close this in that case.
