### ISSUE TITLE
whisper fail to load if path contains hebrew

### ISSUE THREAD

**Issue by thewh1teagle** [tazz4843/whisper-rs#139]
If the model path / the audio path contains Hebrew characters, eg: בדיקה
It crash and won't load.
Looks like whisper expects char *path
Not sure if we can control it

https://github.com/thewh1teagle/vibe/issues/42

**Comment by tazz4843** [comment]
Looking upstream at your issue https://github.com/ggerganov/whisper.cpp/issues/2052 doesn't look like there isn't much we can do, but we can leave this open for whenever upstream fixes it.

**Comment by thewh1teagle** [comment]
There's chance that this reproduce happens because windows terminal doesn't handle the input correctly

**Comment by thewh1teagle** [comment]
Fixed in https://github.com/ggerganov/whisper.cpp/issues/2052
