### ISSUE TITLE
Why is setting RUSTFLAGS required?

### ISSUE THREAD

**Issue by double-daruma** [tazz4843/whisper-rs#14]
In the README you mention that it might be necessary to set `RUSTFLAGS="-Clink-args=-lstdc++"`. Would it be possible to do that in the build.rs within `whisper-rs` ?

**Comment by tazz4843** [comment]
The current git version of the library automatically does this already. It's only required if you're using the crates.io version.

**Comment by tazz4843** [comment]
This was fixed last week in the crates.io version.
