### ISSUE TITLE
Upgrade whisper.cpp to v1.1.1?

### ISSUE THREAD

**Issue by wasd96040501** [tazz4843/whisper-rs#15]
Upgrade whisper.cpp to v1.1.1?

**Comment by tazz4843** [comment]
I've got v1.2 upgrade in the works on my laptop right now. Should be able to release in a few hours.

**Comment by FlakM** [comment]
Awesome! 🥳

**Comment by tazz4843** [comment]
v0.4 has been released to crates.io with the changes in latest v1.2 of whisper.cpp!
