### ISSUE TITLE
Max len has no effect

### ISSUE THREAD

**Issue by weisrc** [tazz4843/whisper-rs#16]
Hi, I am trying to do word level timestamps, however `set_max_len(1)` doesn't do the desired behavior as demonstrated using CLI tool and `-ml 1`.

This is the code:
```rs
let mut whisper_params = FullParams::new(SamplingStrategy::default());
whisper_params.set_max_len(1);
```

Thanks!

**Comment by tazz4843** [comment]
max_len may only have an effect if you use the raw FFI callbacks to get data. That's the only difference I can see between the default Rust usage and the main example. I have never used the FFI callbacks so can't help much with them.

**Comment by weisrc** [comment]
Is the raw FFI callback the `new segment callback`?

**Comment by tazz4843** [comment]
Yes

**Comment by weisrc** [comment]
Hi, the issue is because I did not `set_token_timestamps(true)`. 
I get the expected behavior with the following code:

```rs
let mut whisper_params = FullParams::new(SamplingStrategy::default());
whisper_params.set_token_timestamps(true);
whisper_params.set_max_len(1);
```

Closing this as it is resolved.
