### ISSUE TITLE
Linker errors when using whisper-rs as an external crate

### ISSUE THREAD

**Issue by jyash8** [tazz4843/whisper-rs#164]
When I am using whisper-rs as an external crate in my project I am getting linker errors, although i am not getting any errors when i am compiling the example inside the crate's folders. 
Here are my compiler logs after running "cargo build":
[log.txt](https://github.com/user-attachments/files/16262056/log.txt)

**Comment by jyash8** [comment]
Also can you please tell me about other additional dependencies that are required.

**Comment by tazz4843** [comment]
This error just shows a lot of Rust stdlib functions failing to link. This is definitely not a whisper-rs issue, and it's kinda surprising anything on your system compiles given the error. I suggest trying to figure out what's wrong with your build environment: perhaps try another distro or something.

**Comment by jyash8** [comment]
I checked, other projects were compiling fine. But I was able to fix the issue by using "nightly" channel and it is working fine now.
