### ISSUE TITLE
Add turbo model

### ISSUE THREAD

**Issue by boludoz** [tazz4843/whisper-rs#185]
Please add turbo model please

**Comment by tazz4843** [comment]
https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-large-v3-turbo.bin Already supported upstream as far as I can tell

**Comment by boludoz** [comment]
It is necessary to add the code

**Comment by boludoz** [comment]
![image](https://github.com/user-attachments/assets/ab263c42-1b5a-4246-b1e9-dc3f29e4b8b5)

**Comment by tazz4843** [comment]
Use latest git master of whisper-rs if you want this. No crates.io release will be made until upstream pushes out a stable release.

**Comment by boludoz** [comment]
Thank you sir, I'll look into how to do it later. I'm creating a small web server for me and my friends that converts my voice notes to text and having an API in the rust backend would be useful.
