### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by FireFragment** [tazz4843/whisper-rs#191]
[Documentation on docs.rs](https://docs.rs/crate/whisper-rs/latest) is currently broken.

![Screenshot_20241121_172051](https://github.com/user-attachments/assets/d5eb8364-fcec-477e-89a6-6e7bf8531d7c)

PS: Thank you for maintaining the bindings :)

**Comment by tazz4843** [comment]
0.13.2 finally fixes this

**Comment by FireFragment** [comment]
Thanks! :)
