### ISSUE TITLE
Does have a way to load the model only once and use it for multi audio file in the same time?

### ISSUE THREAD

**Issue by farmer00317558** [tazz4843/whisper-rs#28]
I want to process multi audio files in the same time instead process them one by one.

I tried making the WhisperContext as a Singleton, but when got an error:

```
Assertion failed: (sum > 0.0f), function ggml_compute_forward_flash_attn_f16, file ggml.c, line 6299.
```

Maybe it's a problem of whisper.cpp.

**Comment by tazz4843** [comment]
whisper.cpp does not support this, you must load a new model for each thread.

**Comment by tazz4843** [comment]
whisper.cpp version 1.3.0 was released two days ago, and should support this now. I'll be working on adding the features into whisper-rs tonight.
