### ISSUE TITLE
Is there a way to cancel the transcription process？

### ISSUE THREAD

**Issue by farmer00317558** [tazz4843/whisper-rs#50]

**Comment by tazz4843** [comment]
Nope. This would be an issue for whisper.cpp, not for this project, however.

**Comment by farmer00317558** [comment]
@tazz4843

Can this do that? https://github.com/ggerganov/whisper.cpp/pull/194

**Comment by tazz4843** [comment]
That is exposed: see https://docs.rs/whisper-rs/latest/whisper_rs/struct.FullParams.html#method.set_start_encoder_callback

You will need to handle unsafe code yourself however. I have no plans to make this a safe Rust wrapper, however if you'd like to do so, feel free to make a PR.

**Comment by farmer00317558** [comment]
@tazz4843 

I’ve only been getting to know Rust for a few days, when I am good at it, I’d love to, but Rust is really hard.
