### ISSUE TITLE
Can not build with --target=x86_64-apple-darwin on Mac M1

### ISSUE THREAD

**Issue by farmer00317558** [tazz4843/whisper-rs#56]
Hi,

When I build my rust project with `--target=x86_64-apple-darwin`.

```bash
cargo build --target=x86_64-apple-darwin
```

Encountered the following error:

```
  = note: ld: in /Users/farmer/Projects/my-project/rust/target/x86_64-apple-darwin/debug/deps/libwhisper_rs_sys-cb1bd74588817382.rlib(ggml.c.o), archive member 'ggml.c.o' with length 244616 is not mach-o or llvm bitcode file '/Users/farmer/Projects/my-project/rust/target/x86_64-apple-darwin/debug/deps/libwhisper_rs_sys-cb1bd74588817382.rlib'
```

**Comment by tazz4843** [comment]
Cross building might not be supported by upstream, you may have to build on the target host.

**Comment by tazz4843** [comment]
The upstream project, whisper.cpp itself, may not fully support cross compilation. whisper.cpp itself definitely supports x86_64 Macs, as I've seen issues on this repo mentioning x86_64 on MacOS working fine. You'd probably have to pass some flags to CMake to see if it works. From a quick internet search, I found this: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html but it looks like a huge headache to implement without turning build.rs into a mess.

**Comment by tazz4843** [comment]
I did find ggerganov/whisper.cp#514, but that gives little to no help.

**Comment by farmer00317558** [comment]
@tazz4843 

It looks that adding below command into CMakeLists.txt can output the dylib file supporting both x86_64 and arm64 arch.

```cmake
set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
```

**Comment by tazz4843** [comment]
You'd have to make a PR to upstream and wait for it to be released before this can get upgraded.

**Comment by richtermb** [comment]
@farmer00317558 did you ever figure this issue out? Getting the same error when building (M1 Max).

**Comment by farmer00317558** [comment]
> @farmer00317558 did you ever figure this issue out? Getting the same error when building (M1 Max).

I abandoned the library, wrote a C++ file myself that references the whisper.cpp directly, and built a dynamic library for my project.

**Comment by richtermb** [comment]
@farmer00317558 that's really cool. Would you mind sharing the code with me?

**Comment by farmer00317558** [comment]
@richtermb https://github.com/farmer00317558/hello-dart-ffi 

Here, I hope that helps.

**Comment by tazz4843** [comment]
Gonna close this due to age, if you've resolved it feel free to let us know.
