### ISSUE TITLE
How to install...?

### ISSUE THREAD

**Issue by chris-english** [tazz4843/whisper-rs#6]
Imagining I know very little, but noticing that ~/sys/whisper.cpp was an empty dir and resulted in a cargo build result of whisper.h not found, removed it, and at ~/sys level git cloned the 2c281d190b branch and ran, in new terminal
cargo build with this result
~/whisper-rs$ cargo build
   Compiling whisper-rs-sys v0.2.0 (/home/chris/whisper-rs/sys)
   Compiling whisper-rs v0.2.0 (/home/chris/whisper-rs)
error[E0308]: mismatched types
   --> src/whisper_ctx.rs:202:12
    |
202 |         Ok(ret)
    |         -- ^^^ expected `i32`, found struct `whisper_token_data`
    |         |
    |         arguments to this enum variant are incorrect
    |
note: tuple variant defined here
   --> /home/chris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:508:5
    |
508 |     Ok(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^

error[E0609]: no field `print_special_tokens` on type `whisper_full_params`
  --> src/whisper_params.rs:88:17
   |
88 |         self.fp.print_special_tokens = print_special_tokens;
   |                 ^^^^^^^^^^^^^^^^^^^^ unknown field
   |
   = note: available fields are: `strategy`, `n_threads`, `n_max_text_ctx`, `offset_ms`, `duration_ms` ... and 23 others

Some errors have detailed explanations: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `whisper-rs` due to 2 previous errors

How might I move forward?
Thanks in advance

~

**Comment by tazz4843** [comment]
`git submodule init` followed by `git submodule update` in the root directory of the project will pull the correct commit hash and should get you going.
