### ISSUE TITLE
Android library build failing on windows

### ISSUE THREAD

**Issue by soupslurpr** [tazz4843/whisper-rs#65]
Hello, I am on Windows and am trying to build for android, I am using uniffi and was attempting to use whisper-rs from android, but I get an error. If anyone could help, that would be great. Thanks.

cargo build --target x86_64-linux-android --release
   Compiling whisper-rs-sys v0.6.0
   Compiling whisper-rs v0.8.0
error: could not find native static library `whisper`, perhaps an -L flag is missing?

error: could not compile `whisper-rs-sys` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by tazz4843** [comment]
Any updates here? Android from Windows seems to be a sore spot in general.

**Comment by soupslurpr** [comment]
I haven't tried again, I switched to using Candle for running Whisper which is a machine learning library in Rust. Its slower than whisper.cpp for now, but hopefully that will change over time.

**Comment by soupslurpr** [comment]
Just tried, its failing with this, progress?:

error: failed to run custom build command for `whisper-rs-sys v0.8.0 (https://github.com/tazz4843/whisper-rs?rev=2c0d6404b7aa73602e6caeaef6d82743ac43559a#2c0d6404)`

Caused by:
  process didn't exit successfully: `C:\Users\user\projects\transcribro_rs\target\debug\build\whisper-rs-sys-2b55f3c772be31d6\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=c++_shared
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-linux-android
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_linux_android
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=./whisper.cpp\whisper.h
  cargo:rerun-if-changed=./whisper.cpp/ggml.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include/__stddef_max_align_t.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include\stdbool.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\17\include\stdbool.h
  cargo:rerun-if-changed=./whisper.cpp\ggml.h
  CMAKE_TOOLCHAIN_FILE_aarch64-linux-android = Some("C:/Users/user/AppData/Local/Android/Sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake")
  CMAKE_GENERATOR_aarch64-linux-android = None
  CMAKE_GENERATOR_aarch64_linux_android = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-linux-android = None
  CMAKE_PREFIX_PATH_aarch64_linux_android = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-linux-android = None
  CMAKE_aarch64_linux_android = None
  TARGET_CMAKE = None
  CMAKE = None
  running: "cmake" "-Wdev" "--debug-output" "C:\\Users\\user\\projects\\transcribro_rs\\target\\aarch64-linux-android\\debug\\build\\whisper-rs-sys-68c0f7da7391e8bf\\out\\whisper.cpp/" "-DBUILD_SHARED_LIBS=OFF" "-DWHISPER_ALL_WARNINGS=OFF" "-DWHISPER_ALL_WARNINGS_3RD_PARTY=OFF" "-DWHISPER_BUILD_TESTS=OFF" "-DWHISPER_BUILD_EXAMPLES=OFF" "-DWHISPER_METAL=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/user/AppData/Local/Android/Sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\user\\projects\\transcribro_rs\\target\\aarch64-linux-android\\debug\\build\\whisper-rs-sys-68c0f7da7391e8bf\\out" "-DCMAKE_C_FLAGS= --target=aarch64-linux-android23 -DANDROID -ffunction-sections -fdata-sections -fPIC --target=aarch64-linux-android" "-DCMAKE_CXX_FLAGS= --target=aarch64-linux-android -DANDROID -ffunction-sections -fdata-sections -fPIC --target=aarch64-linux-android" "-DCMAKE_ASM_FLAGS= --target=aarch64-linux-android23 -DANDROID -ffunction-sections -fdata-sections -fPIC --target=aarch64-linux-android" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"
  Running with debug output on.
  -- Building for: Visual Studio 17 2022
  -- ANDROID_PLATFORM not set. Defaulting to minimum supported version
  21.
     Called from: [4]   C:/Users/user/AppData/Local/Android/Sdk/ndk/26.1.10909125/build/cmake/android-legacy.toolchain.cmake
                  [3]   C:/Users/user/AppData/Local/Android/Sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake
                  [2]   C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake
                  [1]   C:/Users/user/projects/transcribro_rs/target/aarch64-linux-android/debug/build/whisper-rs-sys-68c0f7da7391e8bf/out/whisper.cpp/CMakeLists.txt
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Error at CMakeLists.txt:3 (project):
    Failed to run MSBuild command:

      C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe

    to get the value of VCTargetsPath:

      MSBuild version 17.8.3+195e7f5a3 for .NET Framework
      Build started 12/22/2023 6:28:21 PM.

      Project "C:\Users\user\projects\transcribro_rs\target\aarch64-linux-android\debug\build\whisper-rs-sys-68c0f7da7391e8bf\out\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj" on node 1 (default targets).
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\user\projects\transcribro_rs\target\aarch64-linux-android\debug\build\whisper-rs-sys-68c0f7da7391e8bf\out\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj]
      Done Building Project "C:\Users\user\projects\transcribro_rs\target\aarch64-linux-android\debug\build\whisper-rs-sys-68c0f7da7391e8bf\out\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj" (default targets) -- FAILED.

      Build FAILED.

      "C:\Users\user\projects\transcribro_rs\target\aarch64-linux-android\debug\build\whisper-rs-sys-68c0f7da7391e8bf\out\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj" (default target) (1) ->
      (_CheckForInvalidConfigurationAndPlatform target) ->
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\user\projects\transcribro_rs\target\aarch64-linux-android\debug\build\whisper-rs-sys-68c0f7da7391e8bf\out\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj]

          0 Warning(s)
          1 Error(s)

      Time Elapsed 00:00:00.10


    Exit code: 1



     Called from: [1]   C:/Users/user/projects/transcribro_rs/target/aarch64-linux-android/debug/build/whisper-rs-sys-68c0f7da7391e8bf/out/whisper.cpp/CMakeLists.txt
  thread 'main' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  stack backtrace:
     0:     0x7ff783507f2a - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:44
     1:     0x7ff78352b79b - core::fmt::rt::Argument::fmt
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\rt.rs:138
     2:     0x7ff78352b79b - core::fmt::write
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\mod.rs:1114
     3:     0x7ff783502ef1 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\io\mod.rs:1763
     4:     0x7ff783507caa - std::sys_common::backtrace::_print
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:47
     5:     0x7ff783507caa - std::sys_common::backtrace::print
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:34
     6:     0x7ff78350a7fa - std::panicking::default_hook::closure$1
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:272
     7:     0x7ff78350a468 - std::panicking::default_hook
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:292
     8:     0x7ff78350aea8 - std::panicking::rust_panic_with_hook
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:731
     9:     0x7ff78350ad8d - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:609
    10:     0x7ff783508be9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:170
    11:     0x7ff78350aaa0 - std::panicking::begin_panic_handler
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:597
    12:     0x7ff7835348e7 - core::panicking::panic_fmt
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\panicking.rs:72
    13:     0x7ff782eb2ce7 - cmake::fail
                                 at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098
    14:     0x7ff782eb2503 - cmake::run
                                 at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1076
    15:     0x7ff782eae3f8 - cmake::Config::build
                                 at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:813
    16:     0x7ff782e99d47 - build_script_build::main
                                 at C:\Users\user\.cargo\git\checkouts\whisper-rs-c8b9fa7c09c8c913\2c0d640\sys\build.rs:141
    17:     0x7ff782e9263b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
    18:     0x7ff782e9120e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
    19:     0x7ff782e9120e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
    20:     0x7ff782e91f01 - std::rt::lang_start::closure$0<tuple$<> >
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\rt.rs:166
    21:     0x7ff7834fdef8 - std::rt::lang_start_internal::closure$2
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\rt.rs:148
    22:     0x7ff7834fdef8 - std::panicking::try::do_call
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:504
    23:     0x7ff7834fdef8 - std::panicking::try
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:468
    24:     0x7ff7834fdef8 - std::panic::catch_unwind
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panic.rs:142
    25:     0x7ff7834fdef8 - std::rt::lang_start_internal
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\rt.rs:148
    26:     0x7ff782e91eda - std::rt::lang_start<tuple$<> >
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\rt.rs:165
    27:     0x7ff782e9a749 - main
    28:     0x7ff783532050 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    29:     0x7ff783532050 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    30:     0x7fffdd38257d - BaseThreadInitThunk
    31:     0x7fffddccaa58 - RtlUserThreadStart
warning: build failed, waiting for other jobs to finish...

**Comment by tazz4843** [comment]
110 was merged, 0.11 is now released which should hopefully fix this.
