### ISSUE TITLE
Issue Running the Example on Windows Following Instructions from #22

### ISSUE THREAD

**Issue by Tetraib** [tazz4843/whisper-rs#68]
Hello Maintainers,

Firstly, thank you for your efforts to maintain and improve this project. It proves itself very useful.

Recently, I've encountered an issue while following the instructions to run the example on windows as suggested in [#22](https://github.com/tazz4843/whisper-rs/issues/22#issue-1650162620). I keep running into this error: `could not find native static library whisper, perhaps an -L flag is missing?`.

From the error, it's not clear to me whether this issue originates from `whisper.cpp` or `whisper-rs`. Can you provide any clarification on that?

For some context, my intended use for this is with Tauri and hence, I'm not sure if I can rely on cross-compilation as a fallback. Any guidance or suggestions on how to get around this issue would be greatly appreciated.

Here's the command I ran:
```
cargo run --example basic_use
```

And here's the output:
```
Compiling winapi-x86_64-pc-windows-gnu v0.4.0
Compiling winapi v0.3.9
...
...
Compiling whisper-rs-sys v0.6.1
Compiling whisper-rs v0.8.0

error: could not find native static library whisper, perhaps an -L flag is missing?
```

Thank you in advance for your time and any assistance you can provide.

Regards,
Thibaut

**Comment by tazz4843** [comment]
I have no access to Windows systems, so unfortunately I'm unable to help here. However, I do believe a similar error was encountered previously if a Git submodule was not initialized. It appears you're using the crates.io version, however, so this shouldn't be relevant.

**Comment by Tetraib** [comment]
I git cloned whisper-rs to compile it. You believe it has something to do with the cloning of the whisper.cpp inside sys folder ?

**Comment by Tetraib** [comment]
I made sure to use --recursive but run into the same issue :
```
cargo run --example basic_use
Compiling whisper-rs-sys v0.6.1 (C:\whisper-rs\sys)
Compiling whisper-rs v0.8.0 (C:\whisper-rs)
error: could not find native static library `whisper`, perhaps an -L flag is missing?
```
Is there a way to add verbose to the compiling process ? The error message is pretty vague.

**Comment by Tetraib** [comment]
I went with a clean windows vm. Was able to build first try using MSVC. I will try to repeat the steps and write it down, might be useful for someone else.
Thank you for the reply and help.
