### ISSUE TITLE
whisper-rs-sys is likely compiled without AVX support

### ISSUE THREAD

**Issue by marmistrz** [tazz4843/whisper-rs#78]
The fix is proposed here: https://github.com/ggerganov/whisper.cpp/pull/1174

**Comment by tazz4843** [comment]
Given how long it's been since an upstream release I'm probably just going to end up picking the latest git master and making a new release.

**Comment by marmistrz** [comment]
Strangely enough, I looked more closely into this, and even though whisper.cpp itself was compiled without AVX, I can't reproduce it with whisper-rs

**Comment by tazz4843** [comment]
See #85
