### ISSUE TITLE
how to use tdrz params?

### ISSUE THREAD

**Issue by daidi** [tazz4843/whisper-rs#80]
very useful tools , thanks a lot for your efforts!!!

there is one more question ,how can i use tdrz param?
```
-tdrz,     --tinydiarize       [false  ] enable tinydiarize (requires a tdrz model)
```

**Comment by tazz4843** [comment]
whisper.cpp has not made a release in the time since tdrz was released, so that functionality simply doesn't exist downstream yet.

**Comment by tazz4843** [comment]
See #85

**Comment by nipierre** [comment]
Hi @tazz4843, maybe I've missed something about diarization, but aren't we missing bindings to `whisper_full_get_segment_speaker_turn_next` method (cf. https://github.com/ggerganov/whisper.cpp/pull/1058#issuecomment-1761079159) to make it properly working ?
I'm ATM unable to get speaker change information even though I enable `set_tdrz_enable`.

**Comment by tazz4843** [comment]
#99 should have added that method @nipierre

**Comment by nipierre** [comment]
Ok missed it !
Is there any plan to build a function around it ? I can test stuff and push it afterwards if necessary.
