### ISSUE TITLE
real-time processing

### ISSUE THREAD

**Issue by daidi** [tazz4843/whisper-rs#82]
I aspire for my program to acquire the real-time processing outcomes while in operation, enabling the transmission of notifications to the foreground about the ongoing data manipulation through the means of something like events emit.

**Comment by daidi** [comment]
Is this feasible?

**Comment by tazz4843** [comment]
If you just want to show a status bar to the user, you'd likely be fine with [`set_progress_callback`](https://docs.rs/whisper-rs/latest/whisper_rs/struct.FullParams.html#method.set_progress_callback). If on the other hand you want to show the actual output to the user in real time, there's nothing really *designed* for it but you could probably hack something together with [`set_filter_logits_callback`](https://docs.rs/whisper-rs/latest/whisper_rs/struct.FullParams.html#method.set_filter_logits_callback)

**Comment by daidi** [comment]
thank you for your kind reply

**Comment by daidi** [comment]
maybe it could potentially be a feature that can be implemented natively in the future.

**Comment by tazz4843** [comment]
I doubt that would be done, as the architecture of Whisper itself was never really designed for such a thing, as Whisper always pads audio segments to at least 30 seconds, making it relatively inefficient to do real time transcription.
