### ISSUE TITLE
Whisper.cpp 1.5!

### ISSUE THREAD

**Issue by cenzovit** [tazz4843/whisper-rs#98]
Whisper.cpp has finally stabilized to a new version, [1.5.0](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.5.0)! Would it be possible to bump whisper-rs to match?

**Comment by tazz4843** [comment]
It's currently 2330 where I am, however I will indeed take a look in the morning and work on this. Thanks for letting me know :)

**Comment by codesoda** [comment]
This would pull in my whisper.cpp update for ggml-metal.metal, as referenced at https://github.com/tazz4843/whisper-rs/issues/95#issuecomment-1789789129. 🙏

**Comment by tazz4843** [comment]
Some testing on the branch would be nice since there were some changes that broke Windows CI for a bit there, not sure if I broke it more on other platforms and don't want to merge a broken PR. See #99

**Comment by codesoda** [comment]
@tazz4843 Found a few issues, added a PR https://github.com/tazz4843/whisper-rs/pull/100

**Comment by codesoda** [comment]
@tazz4843 few more fixes at https://github.com/tazz4843/whisper-rs/pull/101

**Comment by tazz4843** [comment]
`whisper-rs` 0.10.0 published on crates.io (skipped 0.9 series) along with -sys 0.8 with whisper.cpp 1.5 :)
